### ISSUE TITLE
global config defaults are overwriting shareable configs

### ISSUE THREAD

**Issue by ikatyang** [singapore/renovate#708] opened 2017-08-21 02:59 UTC
I'm not sure if this is only for lockfile maintenance, but there's something wrong with the timezone option, I set the timezone to UTC+8 with default lockfile maintenance schedule (before 5am monday) in my [renovate-config-ikatyang](https://github.com/ikatyang/renovate-config-ikatyang/blob/v1.0.0/package.json#L29) yesterday, but renovate [raised the PR](https://github.com/ikatyang/dts-element/pull/36) at 08:27 (UTC+8) = 00:27 (UTC+0 default timezone), it seems the timezone option did not be set properly.

**Comment by rarkins** [comment] 2017-08-21 04:37
So
- Shareable config is otherwise working?
- Schedule for lock file maintenance seems working (e.g. only once per week)?
- Timezone appears to be being ignored?

**Comment by ikatyang** [comment] 2017-08-21 04:47
> - Shareable config is otherwise working

I'm not sure since there is no updates from my dependencies recently and the lockfile maintenance seems enabled by default.

> - Schedule for lock file maintenance seems working (e.g. only once per week)?

Yeah, it seems working but without shared timezone.

> - Timezone appears to be being ignored?

From the PRs this morning, yes.

**Comment by rarkins** [comment] 2017-08-21 04:51
I've checked the logs and can confirm that the config is resolving to have a `null` timezone. So not directly related to lockFileMaintenance so I'll rename issue.

Here it is in full:

```
   "major": {
      
    },
    "repoForceRebase": true,
    "prCreation": "immediate",
    "branchPrefix": "renovate\/",
    "reviewers": [
      
    ],
    "requiredStatusChecks": [
      
    ],
    "labels": [
      
    ],
    "semanticCommits": true,
    "onboarding": true,
    "devDependencies": {
      "pinVersions": true,
      "description": [
        "Use version pinning (maintain a single version only and not semver ranges)"
      ],
      "semanticPrefix": "chore(deps):"
    },
    "api": "[Function]",
    "packagePatterns": [
      
    ],
    "respectLatest": true,
    "ignoreFuture": true,
    "timezone": null,
    "peerDependencies": {
      "pinVersions": false,
      "enabled": false,
      "description": [
        "Preserve (but continue to upgrade) any existing semver ranges"
      ],
      "semanticPrefix": "chore(deps):"
    },
    "packageNames": [
      
    ],
    "rebaseStalePrs": false,
    "description": [
      "Use <code>renovate\/<\/code> as prefix for all branch names",
      "If semantic commits detected, use <code>fix(deps):<\/code> for dependencies and <code>chore(deps):<\/code> for all others",
      "Require all status checks to pass before any automerging",
      "Update existing lock files only when <code>package.json<\/code> is modified",
      "Pin dependency versions for <code>devDependencies<\/code> and retain semver ranges for others"
    ],
    "errors": [
      
    ],
    "group": {
      "prBody": "[Template]",
      "commitMessage": "[Template]",
      "branchName": "{{branchPrefix}}{{groupSlug}}",
      "recreateClosed": true,
      "prTitle": "[Template]"
    },
    "groupName": null,
    "branchprefix": "renovate\/",
    "commitMessage": "[Template]",
    "schedule": [
      
    ],
    "recreateClosed": false,
    "autodiscover": false,
    "platform": "github",
    "separatePatchReleases": false,
    "packageFiles": [
      {
        "content": "[content]",
        "hasYarnLock": true,
        "hasPackageLock": false,
        "packageFile": "package.json"
      }
    ],
    "prBody": "[Template]",
    "logger": "[Function]",
    "excludePackagePatterns": [
      
    ],
    "minor": {
      
    },
    "packageRules": [
      {
        "packageNames": [
          "typescript"
        ],
        "automerge": "patch"
      }
    ],
    "isGitHub": true,
    "repository": "ikatyang\/dts-element",
    "prTitle": "[Template]",
    "pinVersions": true,
    "optionalDependencies": {
      "pinVersions": false,
      "description": [
        "Preserve (but continue to upgrade) any existing semver ranges"
      ],
      "semanticPrefix": "chore(deps):"
    },
    "separateMajorReleases": true,
    "semanticPrefix": "chore(deps):",
    "ignoreUnstable": true,
    "dependencies": {
      "pinVersions": false,
      "description": [
        "Preserve (but continue to upgrade) any existing semver ranges"
      ],
      "semanticPrefix": "fix(deps):"
    },
    "automergeType": "pr",
    "lockFileMaintenance": {
      "schedule": [
        "before 5am on monday"
      ],
      "commitMessage": "[Template]",
      "prTitle": "[Template]",
      "enabled": true,
      "recreateClosed": true,
      "groupName": "Lock File Maintenance",
      "prBody": "[Template]",
      "branchName": "{{branchPrefix}}lock-file-maintenance"
    },
    "baseBranch": null,
    "ignoreNodeModules": true,
    "endpoint": null,
    "ignoreDeps": [
      
    ],
    "automerge": "none",
    "versions": {
      "npm": "5.3.0",
      "renovate": "9.43.10"
    },
    "unpublishSafe": false,
    "isFork": false,
    "enabled": true,
    "groupSlug": null,
    "excludePackageNames": [
      
    ],
    "patch": {
      "branchName": "{{branchPrefix}}{{depName}}-{{newVersionMajor}}.{{newVersionMinor}}.x"
    },
    "assignees": [
      
    ],
    "token": null,
    "privateRepo": false,
    "renovateJsonPresent": true,
    "lazyGrouping": true,
    "warnings": [
      
    ],
    "branchName": "{{branchPrefix}}{{depName}}-{{newVersionMajor}}.x"
```

**Comment by ikatyang** [comment] 2017-08-21 05:02
Wait, it seems some sharable configs are also not applied?!

The `schedule` (`[]`), `automerge` (`none`), `labels` (`[]`) from your log, they're not override by my configs.

Here's my config (I'm using `ikatyang:library` for all my repos).

```json
  "renovate-config": {
    "default": {
      "extends": [
        ":renovatePrefix",
        ":semanticPrefixFixDepsChoreOthers",
        ":automergeRequireAllStatusChecks",
        ":maintainLockFilesWeekly"
      ],
      "timezone": "Asia/Taipei",
      "schedule": ["before 8am"],
      "semanticCommits": true,
      "separateMajorReleases": true,
      "separatePatchReleases": false,
      "ignoreUnstable": true,
      "respectLatest": true,
      "rebaseStalePrs": true,
      "prCreation": "immediate",
      "automerge": "minor",
      "automergeType": "pr",
      "unpublishSafe": false,
      "labels": ["dependencies"]
    },
    "library": {
      "extends": ["ikatyang:default", ":pinOnlyDevDependencies"]
    }
  }
```

**Comment by rarkins** [comment] 2017-08-21 05:04
Thanks, it's probably the same bug causing them all :-/

**Comment by rarkins** [comment] 2017-08-21 05:20
OK, I know what the problem is, but need to work out how to fix.

Config is applied left to right, what it should be is this:

Global <- first extends <- second extends <- last extends <- non-extends config

But instead it's being evaluated like:

first extends <- second extends <- last extends <- Global <- non-extends config

so therefore these global defaults of null or [] are overriding extends config.

**Closed** 2017-08-21 08:19 UTC
Labels: fix, in progress, pri2-important
