### ISSUE TITLE
Squashing commits in a given branch?

### ISSUE THREAD

**Issue by Phyks** [singapore/renovate#1052] opened 2017-10-28 17:18 UTC
Hi,

Sometimes `renovate` suggests updates for a module, and as we take some time to merge the MR, new updates get pushed to this branch.

That's super practical that `renovate` is able to push all new versions in the same branch, leading to a single MR per dep and not one per version. However, the commit history looks like:

* Update X to v1
* Update X to v2
* Update X to v3

Which makes some useless commits in the history. Is there an option to make renovate squash its commits to have a single commit updating to v3, with all the history in its description?

What do you think about adding such an option if it's not available?

Thanks!

**Comment by rarkins** [comment] 2017-10-28 17:39
@Phyks thanks for the suggestion. This should already be the default behaviour, since about a week ago. The PR I implemented it in is here: https://github.com/singapore/renovate/pull/1018

The aim of this was to have a single commit per branch in all cases except where end users start editing the branch themselves, in which case we just add any new commits on top instead of squashing.

Maybe I didn't test all possibilities, or maybe it broke since then, or maybe you were looking at older examples or running older code? If you think this is still happening with the recent code, then I need either steps to reproduce it, or some debug logs of it happening.

(FYI: we don't technically `git rebase` or `git squash` but I use those terms as they are most understandable for people)

**Comment by Phyks** [comment] 2017-10-28 17:44
Oh, indeed I completely missed this PR in my search. I am running last tagged version, which is quite old it seems. I will just move to the `master` branch :)

**Comment by rarkins** [comment] 2017-10-28 17:52
Actually the npm release is essentially never "behind" master because we use `semantic-release` to bump version and release on almost every commit. The latest was 20 hours ago: https://www.npmjs.com/package/renovate

If you're seeing the "old" behaviour (incremental commits to existing PR) with a recent `renovate` version then it sounds like something is wrong.

**Comment by rarkins** [comment] 2017-10-28 17:52
Also, in that PR I used term rebase but now I'm thinking "squash" would have been much better

**Comment by Phyks** [comment] 2017-10-28 17:54
Actually, I followed [these instructions](https://github.com/singapore/renovate/blob/master/docs/deployment.md#heroku) so I am in sync with an old `master` branch I think. I will update and let you know!

**Comment by rarkins** [comment] 2017-10-28 19:06
ok, I got it. I'll close this then, please reopen if you don't see the behaviour you expect.

**Closed by rarkins** 2017-10-28 19:06 UTC
Labels: needs-requirements, pri4-low

**Comment by Phyks** [comment] 2017-10-28 21:13
Sure, thanks!
